---
title: "HW13: Strings and things"
author: "Amanda Russom"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options:
  chunk_output_type: inline
---

```{r}
library(tidyverse)
library(here)
library(ggthemes)
```

### Import beta_gliadin data
```{r}
beta_gliadin_raw <- read_lines(here("Data", "beta_gliadin.txt"),skip = 1)
beta_gliadin_raw
```

### replace whitespace and digits with nothing
```{r}
beta_gliadin_cleaned <- str_replace_all(beta_gliadin_raw,"\\d","") %>% 
  str_replace_all("\\s", "")
beta_gliadin_cleaned
  
```
### Collapse the strings
```{r}
beta_gliadin_collapsed <- str_c(beta_gliadin_cleaned, collapse = "")
beta_gliadin_collapsed
```

### Convert to upper case and return length
```{r}
beta_g_upper <- str_to_upper(beta_gliadin_collapsed) 
beta_g_upper
```
### find length of sequence
```{r}
str_length(beta_g_upper)
```


### count the letters that are not A, C, G, T
```{r}
str_count(beta_g_upper, ".A.C.G.T")
```
### Count start codons 
```{r}
str_count(beta_g_upper, "ATG")
```
### Count stop codons
```{r}
str_count(beta_g_upper, "TGA|TAA")
```


